try{
    let x=5;

let sum=x+y;
console.log(sum);
}
catch(error){
    console.error(error.message);
    
}

finally{
    console.log("hi");
    
}

